spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb
    username: demo
    password: demo
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: true

