spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb
    username: demo
    password: demo
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: true
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
        region: us-east-2